### ISSUE TITLE
Fail in a scenerio

### ISSUE THREAD

**Issue by ankitaggarwal-trantor** [johnmee/codility#1]
If I enter the input like: _solution(3, [3, 3, 1, 1, 4])_, its showing _4_ output. It should show _-1_, because _2_ index does not exists in list and frog can only cross if all (1 to X) positions are filled.

**Comment by johnmee** [comment]
You're right.

The algorithm mistakenly assumes that all the recorded leaves are between 0 and X.

Can you submit a fix?
