### ISSUE TITLE
MaxCounters Question wrong Example answer

### ISSUE THREAD

**Issue by mboyr4z** [johnmee/codility#15]
solution(1, [1,2,2]), [2]),

you wrote the answer [2]. but the answer should be [1]

in Test_Singles, place 3.

**Comment by johnmee** [comment]
Note that the assert is opposite to the others.  It asserts that the answer is **NOT** EQUAL to [2]

    def test_singles(self):
        self.assertEqual(solution(1, [1]), [1])
        self.assertEqual(solution(1, [1, 2]), [1])
        self.assertNotEqual(solution(1, [1,2,2]), [2])
        self.assertEqual(solution(1, [1, 1, 2, 1, 1]), [4])

**Comment by mboyr4z** [comment]
Ow ty
